--
-- -- --Dodavanje korisnika
-- -- insert into app_user(id, address, email, firstname, lastname, password, role, username, verified)
-- --   values (1, 'MarijeBursac15', 'zarko_drageljevic@hotmail.com', 'Zarko', 'Drageljevic', '123', 'USER', 'Zarko', 1);
-- --
-- -- insert into app_user(id, address, email, firstname, lastname, password, role, username, verified)
-- --   values (2, 'MarijeBursac15', 'petarpetar@mailinator.com', 'Petar', 'Petrovic', '123', 'USER', 'Petar', 1);
-- --
-- -- insert into app_user(id, address, email, firstname, lastname, password, role, username, verified)
-- --   values (3, 'MarijeBursac15', 'mirkomirko@mailinator.com', 'Mirko', 'Mirkovic', '123', 'USER', 'Mirko', 1);
-- --
-- -- insert into magazine(id,open_access) values (1,true);
-- -- insert into magazine(id,open_access) values (2,true);
-- -- insert into magazine(id,open_access) values (3,false);
--
-- -- insert into magazine_subscriptions(magazine_id, subscriptions_id) values (1,1);
--
-- insert into scientific_field( id, title) values (1, 'Matematika');
-- insert into scientific_field( id, title) values (2, 'Biologija');
-- insert into scientific_field( id, title) values (3, 'Programiranje');
-- insert into scientific_field( id, title) values (4, 'Hemija');
--
-- insert into scientific_field_reviewers (science_fields_id, reviewers_id) values (1,6);
-- insert into scientific_field_reviewers (science_fields_id, reviewers_id) values (3,6);
-- insert into scientific_field_reviewers (science_fields_id, reviewers_id) values (2,10);
-- insert into scientific_field_reviewers (science_fields_id, reviewers_id) values (4,10);
-- insert into scientific_field_reviewers (science_fields_id, reviewers_id) values (1,11);
-- insert into scientific_field_reviewers (science_fields_id, reviewers_id) values (2,11);
-- insert into scientific_field_reviewers (science_fields_id, reviewers_id) values (3,11);